### ISSUE TITLE
ESPhome eventually bricks Mirabella RGBW Striplight

### ISSUE THREAD

**Issue by ock666** [esphome/issues#1586]
**Operating environment/Installation (Hass.io/Docker/pip/etc.):**

VM
**ESP (ESP32/ESP8266, Board/Sonoff):**

esp01_1m
**ESPHome version (latest production, beta, dev branch)**

1.14
**Affected component:**

**Description of problem:**
After a month of use ESPhome has bricked my RGB strip, no backup AP, cant find it in router attached devices.
Making the software more accessible, forgiving and user friendly would go a long way as this is now the third tuya device thats been bricked using ESPhome either straight after flashing or after maybe a month of use. Its getting expensive and exhausting and I dont want to use this software any more.

**Problem-relevant YAML-configuration entries:**
```yaml
PASTE YAML FILE HERE

```
https://esphome-configs.io/devices/mirabella-genio-wifi-led-strip-light/
**Logs (if applicable):**

```
PASTE DEBUG LOG HERE

```

**Additional information and things you've tried:**

**Comment by CarlosGS** [comment]
Not sure. However the example in <https://github.com/jonathanadams/esphome-configs/blob/master/_devices/Mirabella-Genio-WiFi-LED-Strip-Light/Mirabella-Genio-WiFi-LED-Strip-Light.md> can be a bit misleading as it sets multiple passwords manually.

I think the recommended practice is to leave these fields empty so HASS takes care of the API and OTA passwords.
```
# Enable Home Assistant API
api:

# Setup OTA password
ota:
```
I am not sure on how the passwords are generated internally, how did you choose them?

Otherwise I still don't know how could they get randomly bricked. Maybe a captive portal bug? (I recall its not very stable, but not sure it would cause a brick). So, which version of everything are you running?
