### ISSUE TITLE
Monochromatic Light don't dim with HA

### ISSUE THREAD

**Issue by xtimmy86x** [esphome/issues#2355]
### The problem

After the last update 2018.8.1 all my monochromatic lights don't show the dim bar in Home Assistant 2018.8.8
with the previous version 2018.8,0 all is ok

### Which version of ESPHome has the issue?

2018.8.1

### What type of installation are you using?

Docker

### Which version of Home Assistant has the issue?

2018.8.8

### What platform are you using?

ESP32

### Board

ESP32 dev

### Component causing the issue

monochromatic light

**Comment by glyndon** [comment]
same here. Posted about it on the HA forum: https://community.home-assistant.io/t/2021-8-1-breaks-monochromatic-light/332648

**Comment by kernelpanic85** [comment]
Just upgraded and seeing the same issues as well

**Comment by 3ative** [comment]
Same:
All my mono lights have **'color modes'** (_not needed_) and no **'Brightness'** now. :(
![image](https://user-images.githubusercontent.com/51385971/130727212-cb48138f-a447-4b8d-87c6-1e9ccb45ef58.png)

**Comment by wendelit** [comment]
I've been trying to understand the ESP home code to try and figure out this problem, and this is a wild guess, but can it be because the protocol buffer code is complied and needs to be re-compiled to take this update into account ?

**Comment by jesserockz** [comment]
The issue is that there was a mistake in the color_mode value for monochromatic which made it `2` instead of `3`.

There was also a mistake of including this change in 2021.8.1 when it should have waited until the next release as Home Assistant needs to be updated to recognise `3` (as well as `2` for a period of time).

I could revert the change in ESPHome, but it will need to be made again soon anyway.
