### ISSUE TITLE
Won´t connect to wifi network

### ISSUE THREAD

**Issue by wassereimer86** [esphome/issues#2617]
### The problem

wifi:
  ssid: "Das ist ein laengerer Name"
  password: "fgeR_,v%*Q\lE=xNa_Tep'y8ZwbvF{"

Doesn´t work. If i use a simple AP on my smartphone with the following credentials, it works.

wifi:
  ssid: "Name"
  password: "test1234"

Escaping the "\" with an extra "\" doesn´t work. The fallback AP will go live. Changing the password in the AP doesn´t work either.

### Which version of ESPHome has the issue?

2021.10.2

### What type of installation are you using?

Docker

### What platform are you using?

ESP32

### Board

esp32cam

### Component causing the issue

WiFi Component

### Example YAML snippet

```yaml
wifi:
  ssid: "Das ist ein laengerer Name"
  password: "fgeR_,v%*Q\lE=xNa_Tep'y8ZwbvF{"
```

**Comment by wassereimer86** [comment]
Does anybody has ideas? 😕

**Comment by wassereimer86** [comment]
Tasmota has no problem connecting to my network. So it´s a problem with ESPHome.

**Comment by mmakaay** [comment]
Like @OttoWinter suggested, try using the escape tool.
If you enter a `\l` in there, you'll see that it gets escaped as `\\l`. 
I think that currently, the `\l` in your config gets translated on only `l`, which is unlikely what you wanted there.

So try the following:
```yaml
wifi:
  ssid: "Das ist ein laengerer Name"
  password: "fgeR_,v%*Q\\lE=xNa_Tep'y8ZwbvF{"
```

**Comment by wassereimer86** [comment]
As i wrote:
`The online escape tool does exactly the same.

The config / validate command spits out the password how it should be.`

I also entered to password in the website from the "Access Point" after directly connecting to the AP. This also didn´t work. And there i don´t have to escape the password i guess?

I also tried multiple different escapings before posting here.

With Tasmota i entered my credentials in the AP it created and it worked without a problem. I would love to use ESPHome but i´m not willing to change my Wifi SSID and password from my router.

**Comment by mmakaay** [comment]
It's really a bit unclear what escapings you actually tried. The only thing I can comment on, is the password as you showed it in your initial posting, and that one contains the `\l`, which does not make sense to me. So that's why I posted an alternative, of which I'm curious if that works or not.

You don't have to change your AP password, I don't think anybody is telling you to do so.

You are right that if the fallback access point doesn't handle backslashes correctly, that this could very well indicate a bug in the string handling. However, to not be handling multiple issues all in one go, I'm just trying to see if we can get to the point where your device connects successfully to your AP, with the desired password. From there we know that this is a working configuration, and we can move on to the next step of being able to setup that configuration from the fallback access point interface.

**Comment by wassereimer86** [comment]
The password i posted here is, of course, not my actual password. Same with the SSID. I used similar data but at the end it is completely different.

The password contains the backslash with a letter behind it. I also tried escaping the backslash. I used the Escape tool with my password and when i tried it, it still didn´t work.

Because i don´t have ESPHome installed anymore, i tried it now with ESP Web Tools. Installation worked. I entered my credentials and it fails.

**Comment by mmakaay** [comment]
Just for testing, did you try to enter the backslash escaped?

**Comment by mmakaay** [comment]
I just tried setting up a device using the AP function, using the password with a backslash in it, and this also worked for me.
So I tested two routes now, and both worked:

- Setting up the password using the fallback Access Point function
- Setting up the password in the YAML config, using an escaped `\\`

**Comment by wassereimer86** [comment]
I can give you my real credentials in private if you want to test it with them. Just let me know how i can give them to you.

**Comment by mmakaay** [comment]
You can join [the ESPHome Disord](https://discord.gg/KhAMKrd)
There, you can contact me via PM under the nick "MauriceM".

**Comment by mmakaay** [comment]
@wassereimer86 contacted me on Discord and shared his real credentials. On my network, I created a BSSID + password for those credentials. I also setup a device with the access point on WiFi. After connecting to it, and using the credentials, my device connected successfully. So based on that, it looks like we're not looking at an issue with entering credentials here.

@wassereimer86 tested with complex credentials on a phone AP. Connecting to that did work. So this might indicate that there's a connection issue specifically between the router and the device.

Last check proposed was to setup a guest network on the WiFi router with simple credentials, to see if the device could connect to that. Waiting for the results of that test.

**Comment by wassereimer86** [comment]
It´s working with simple guest network credentials. I used the SSID "Gastzugang" and the password "1234567890".

If i use the same password from my main network with a slightly different SSID (an "m" instead of an "n" from the original SSID) it couldn´t connect.

If i use the same password from my main network with the SSID "Gastzugang" it couldn´t connect.

If i use the password "1234567890" with a slightly different SSID (an "m" instead of an "n" from the original SSID) it couldn´t connect.

So it seems to be the combination of both my credentials.

**Comment by mmakaay** [comment]
So the common factor that this boils down to would be "your router, combined with a long bssid or long password"?
Maybe something to check, would be if it works when you use "Gastzugang" plus a long and simple password like "123456789012345678901234567890". But all in all, it's quite strange behavior I must say.

**Comment by wassereimer86** [comment]
> But all in all, it's quite strange behavior I must say.

Absolutly!

Your suggestion works. Your suggested password with a slightly different SSID (an "m" instead of an "n" from the original SSID) is not working....

**Comment by mmakaay** [comment]
Okay, so while I have no idea what the exact issue is here, we can at least establish that it's not the complex password from the start of this thread, but something else that is interfering with setting up the connection.
And the fact that Tasmota works with the same set of credentials is interesting too.

I do have a spare FRITZ!Box lying around that I could use for testing, but I don't have an ESP32cam board (that's the combiation that you've been testing with, right?) If somebody else could test this, it would be nice. Otherwise I can see if I can get hold of an ESP32cam for experimentation.

**Comment by wassereimer86** [comment]
I have this item https://www.amazon.de/gp/product/B097R45VVQ/

If i can help in any way: Please let me know. It would be great to see logs to see what is going on...

**Comment by mmakaay** [comment]
I ordered a board, but it'll probably take a week or two till it arrives.
By that time, I will do some testing in combination with my FRITZ!Box device.

**Comment by wassereimer86** [comment]
Thank you for your effort!

Meanwhile i tried multiple randomized credentials from my originial SSID und password just to test. Doesn´t work either.

**Comment by wassereimer86** [comment]
Where you able to recreate the problem?

**Comment by mmakaay** [comment]
The board has been delayed, but according to the tracking info it should arrive somewhere next week.

**Comment by wassereimer86** [comment]
Hey there! Do you have any new informations on the topic? 🙂

**Comment by mmakaay** [comment]
If only I could find the power supply for the FritzBox that's sitting next to me :-p I'm in a big house renovation, and the thing is ... somwhere. I got the board after some more delays, so that part is settled now.

**Comment by wassereimer86** [comment]
Just to let you know: I have still the same issue with the latest version. 🤷‍♀️

**Comment by mmakaay** [comment]
The issue seems to be related to the SSID and not the password. I could reproduce the issue with the original WiFi credentials that @wassereimer86 provided to me. I setup a Fritzbox with those credentials and tried to connect an EPS32-CAM device to it. That resulted in a failing connection.

Investigating the issue, I found that the issue probably lies in the fact that the SSID contains 32 bytes. However, the ESPHome code only support up to 31 bytes because of the way in which the wifi library code is used. It does allow for 32 bytes in other bits of code, as it should because that is the RFC limit.

I managed to get the WiFi connection working by changing the WiFi component.
The change that I did is [here](https://github.com/mmakaay/esphome/blob/e53cc3dc1661a2886839294c87f2320f067e7714/esphome/components/wifi/wifi_component_esp32_arduino.cpp#L164)
The change can be tested by adding the following to the YAML config:

```yaml
external_components:
  - source: github://mmakaay/esphome@fix-32-bytes-wifi-ssid
    components: [ wifi ]  
```

Using this with ESPHome version 2022.1.3 resulted in a working WiFi connection for me.

**But...**

While this does work for a successful connection, I do see these logs on failure (using a wrong password):

```
[12:42:27][D][WiFiGeneric.cpp:374] _eventCallback(): Event: 5 - STA_DISCONNECTED
[12:42:27][W][WiFiGeneric.cpp:391] _eventCallback(): Reason: 15 - 4WAY_HANDSHAKE_TIMEOUT
[12:42:27][W][wifi_esp32:500]: Event: Disconnected ssid='********************************' bssid=74:42:7F:21:96:62 reason='4-Way Handshake Timeout'
[12:42:27][W][wifi:557]: WiFi Unknown connection status 0
[12:42:27][W][wifi:557]: WiFi Unknown connection status 0
[12:42:27][W][wifi:557]: WiFi Unknown connection status 0
[12:42:27][W][wifi:557]: WiFi Unknown connection status 0
[12:42:27][W][wifi:557]: WiFi Unknown connection status 0
[12:42:27][W][wifi:557]: WiFi Unknown connection status 0
```

That last log message is shown in what looks like a tight loop.
So some more investigation is needed to see where and why this happens, instead of the device cleanly trying to reconnect.
And when that is done, then some work is needed to fix the same issue for the other frameworks where needed.

**Comment by mmakaay** [comment]
To check if my code didn't do anything illegal, I jumped into the arduino-esp32 code and found [this bit](https://github.com/espressif/arduino-esp32/blob/c4954dd582f5bde478316ddf184ded6979e812b3/libraries/WiFi/src/WiFiSTA.cpp#L56):

```c++
static size_t _wifi_strncpy(char * dst, const char * src, size_t dst_len){
    if(!dst || !src || !dst_len){
        return 0;
    }
    size_t src_len = strlen(src);
    if(src_len >= dst_len){
        src_len = dst_len;
    } else {
        src_len += 1;
    }
    memcpy(dst, src, src_len);
    return src_len;
}
```

This is used to copy the ssid into the config structure by that library code.
The function is called by code that looks like this:

```c++
_wifi_strncpy((char*)wifi_config->sta.ssid, ssid, 32)
```

The target is a `uint8_t[32]`.
So what happens here, is that the `_wifi_strncpy` checks if the provided ssid is shorter than 32 chars using strlen.
If yes, then this means that the ssid is a `\0`-terminated char array. In that case, the number of bytes to copy using `memcpy()` is strlen+1, to copy the `\0` as well.
If no, then the ssid is 32 bytes or more, in which case `memcpy()` will copy the first 32 bytes of the ssid, NOT including the `\0`.

Based on all this, I find that the library has some specific code in place to work with 32 byte long SSID's, by storing the SSID bytes without a `\0` in the target data structure 👍 

Time to look at the other frameworks.

**Comment by mmakaay** [comment]
ESP8266 Arduino and ESP32 ESP-IDF did not have the problem.
I submitted a [pull request](https://github.com/esphome/esphome/pull/3199).

**Comment by mmakaay** [comment]
ESPHome 2022.2.0 was released.
This one contains the fix.
