### ISSUE TITLE
Devices no longer show "Update Available" if OTA fails

### ISSUE THREAD

**Issue by kyleteal** [esphome/issues#2804]
### The problem

When updating devices that state "Update Available" if the OTA process fails (either because it is not on or the connection is bad) the "Update Available" goes away regardless of if the update was successful or not. 

### Which version of ESPHome has the issue?

2021.12.0

### What type of installation are you using?

Home Assistant Add-on

### Which version of Home Assistant has the issue?

2021.12

### What platform are you using?

ESP8266

### Example YAML snippet

```yaml
N/A
```

### Anything in the logs that might be useful for us?

```txt
N/A
```

### Additional information

N/A

**Comment by mmakaay** [comment]
The issue now is that the upgrade indicator is more like a latest-firmware-version-was-built-successfully indictor.
This is a known behavior and there was some discussion about this on the "dashboard" channel on Discord.
Because these days, more information is bundled in the mDNS data, the plan was to use that information to determine upgradability. 
I don't think that a specific issue was created for this, so we can keep this one for tracking it.
