### ISSUE TITLE
MHZ19 CO2 Sensor - different types

### ISSUE THREAD

**Issue by Tokn59** [esphome/issues#2807]
### The problem

There are 2 different types of this sensor. One with a max range of 2000 ppm and one with 5000 ppm range. There seems to be no way to define what sensor you are using. Not sure if it actually makes a difference.

### Which version of ESPHome has the issue?

2021.12.0

### What type of installation are you using?

Home Assistant Add-on

### Which version of Home Assistant has the issue?

2021.12.0

### What platform are you using?

ESP8266

### Board

D1 Mini Pro

### Component causing the issue

MHZ19

### Example YAML snippet

```yaml
Not applicable
```

### Anything in the logs that might be useful for us?

```txt
Not applicable
```

### Additional information

Please advise for what version (2000 or 5000 ppm) the default settings are. THANK YOU !

**Comment by petergebruers** [comment]
There is actually even a third possibility: 0-10000 ppm.

No, it does not matter, because the sensors all report CO2 as 2 bytes and use this formula:

`CO2 concentration = HIGH * 256 + LOW`

This calculation is done for you in ESPHome.

As you can see, there is no "scaling" involved, all types report (true) ppm.
