### ISSUE TITLE
Substitutions and secrets conflicts

### ISSUE THREAD

**Issue by SH-Solutions** [esphome/issues#486]
**Operating environment/Installation (Hass.io/Docker/pip/etc.):**

**ESP8266 Wemos D1 mini R2 Board**

**Affected component:**

substitutions

**Description of problem:**
Its not possible to use "substitutions" together with the "! secret xxx" feature if the required secret contains a "$" sign. And maybe also with "-" (dash) sign?

**Problem-relevant YAML-configuration entries:**
```yaml
PASTE YAML FILE HERE

```

**Logs (if applicable):**

```
INFO Reading configuration...
WARNING Found '$mySecret' (see substitutions->ota_password) which looks like a substitution, but 'mySecret' was not declared
WARNING Found 'my$Se-cret' (see mqtt->password) which looks like a substitution, but 'Se' was not declared
Failed config

```

**Additional information and things you've tried:**

**Comment by OttoWinter** [comment]
1.

Secrets are read first - only after that are substitutions processed. This is intentional and will stay this way (the other option is the other way around, but the current way makes more sense in some cases).

2. 

It's just a warning, not an error. As the message shows, it *looks* like a substitution, but the substitution value was not defined, so the pre-processor will ignore the substitution. This is intentional to protect users from typos.

The failed config is probably due to something else wrong in your config.
