### ISSUE TITLE
Esphome roadmap

### ISSUE THREAD

**Issue by erazor666** [esphome/issues#56]
Is there a roadmap, with whats being worked on, planned features and such? I'm following this project closely and eagerly awaiting any new developments.

Not really an issue but this felt like the most apropriate place for such a question. Keep up the amazing work Otto! :)

**Comment by OttoWinter** [comment]
There's no roadmap - I just add things when I have the time to and it seems like fun to do.

You can find some things on the feature requests section here: https://github.com/esphome/feature-requests
Otherwise maybe follow the commit logs in the repos; long-term planning does not exist for me.

Closing this as meta (discussion can still continue though)
