### ISSUE TITLE
Web Server version 3 doesn't work with local enabled

### ISSUE THREAD

**Issue by pyrodex** [esphome/issues#5692]
### The problem

When using the new "version 3" of the web_server and using "local: true" it only loads the v2 of the web_server component. Removing "local: true" and re-compiling actually provides the v3 of the web_server component.

### Which version of ESPHome has the issue?

2024.3.2

### What type of installation are you using?

Docker

### What platform are you using?

ESP32

**Comment by pzich** [comment]
I believe this is (at least partially) because v3 is still under active development, so there isn't a static [`INDEX_GZ`](https://github.com/esphome/esphome/blob/6a1ea0674469a5c487ee3b83da40e96f6dac792f/esphome/components/web_server/server_index.h) made for it yet, which is what `v2` uses.

As a workaround, you can do the following:
- `curl -O 'https://oi.esphome.io/v3/www.js'` to download the current non-local v3 code
- Use `js_include: "www.js"` and `"js_url": ""` in your `web_server` config so this code is included locally

```
web_server:
  version: 3
  js_include: "www.js"
  js_url: ""
```

This results in the same v3 experience as the non-local, but with the JS being served locally.
