### ISSUE TITLE
High CPU usage while compiling

### ISSUE THREAD

**Issue by koldogut** [esphome/issues#5972]
### The problem

I've running ESPHOME as a docker container on a UNRAID box for at least 6 years but after last 2 versions I noticed compilation process takes 100% CPU. I noticed first a high consume on SHFS process and after some tries I identified ESPHOME compilation process to be triggering this issue. I've also searched many forums and despite having CacheDirs not installed it keeps eating the whole CPU.

![image](https://github.com/esphome/issues/assets/43078880/419f83cd-4e68-47df-b5c5-83edfc3a5f3f)

No matter the code (big or small, Platformio or Arduino) it always rise to the top; once stopped the compilation in the Esphome web, htop continues showing compilation processes for a couple of minutes before ending and then CPU goes back to normal.

My server is a Dell Poweredge T550 64Gb of ECC RAM Intel® Xeon® Silver 4309Y CPU @ 2.80GHz single CPU (8 cores)

### Which version of ESPHome has the issue?

2024.6.2

### What type of installation are you using?

Docker

### Which version of Home Assistant has the issue?

2024.6.4

### What platform are you using?

ESP32

**Comment by ssieb** [comment]
What are you expecting?  That's what happens when you compile things.  If the build system is setup properly, all possible cores will be used for the compile.  And anything that runs for some time will be using 100% CPU.  If you don't want that, you can restrict the number of cores used.  But why would you want to slow it down for no reason?
