### ISSUE TITLE
Issue after updating - esphome: error: argument command: invalid choice:

### ISSUE THREAD

**Issue by Freland** [esphome/issues#6194]
### The problem

After updating docker to latest (running in Synology NAS) esphome won't start.

`esphome: error: argument command: invalid choice: '/config' (choose from 'config', 'compile', 'upload', 'logs', 'log', 'discover', 'run', 'clean-mqtt', 'wizard', 'mqtt-fingerprint', 'version', 'clean', 'dashboard', 'vscode', 'update-all', 'idedata', 'rename')`

Environment variables in container:
<img width="655" alt="Screenshot 2024-08-23 at 10 25 56" src="https://github.com/user-attachments/assets/59f31db1-79b2-47ee-83ed-e6241fbadd31">

### Which version of ESPHome has the issue?

2024.8.0

### What type of installation are you using?

Docker

### What platform are you using?

ESP8266

**Comment by randybb** [comment]
There was a [breaking change](https://esphome.io/changelog/2024.8.0.html#breaking-changes) (yea, it is not very clear what it is doing), so the issue is in your configuration:
`esphome <CONFIG> dashboard` -> `esphome dashboard <CONFIG>` - this has been changed 3 years ago https://github.com/esphome/esphome/pull/1805, the breaking change removed the old syntax. So modify your docker file.
