### ISSUE TITLE
[lvgl -> image] Unable to set the image source via lambda expression

### ISSUE THREAD

**Issue by Valcob** [esphome/issues#6209]
### The problem

trying to set the source of an image through a script fails
```
  # - lvgl.image.update:
  #     id: img_temp_o
  #     src: !lambda |-
  #       return (strcmp(id(yr_sensor).state.c_str(), "partlycloudy")  == 0) ? id(partlycloudy)
  #         : (strcmp(id(yr_sensor).state.c_str(), "cloudy")  == 0) ? id(cloudy)
  #         : (strcmp(id(yr_sensor).state.c_str(), "snowy")  == 0) ? id(snowy)
  #         : (strcmp(id(yr_sensor).state.c_str(), "rainy")  == 0) ? id(rainy)
  #         : (strcmp(id(yr_sensor).state.c_str(), "fog")  == 0) ? id(fog)
  #         : id(sunny);

```
the image is not displayed at all though no issue in the logs and the code compiles successfully 

### Which version of ESPHome has the issue?

2024.8.1

### What type of installation are you using?

Home Assistant Add-on

### What platform are you using?

ESP32

### Example YAML snippet

```yaml
# - lvgl.image.update:
  #     id: img_temp_o
  #     src: !lambda |-
  #       return (strcmp(id(yr_sensor).state.c_str(), "partlycloudy")  == 0) ? id(partlycloudy)
  #         : (strcmp(id(yr_sensor).state.c_str(), "cloudy")  == 0) ? id(cloudy)
  #         : (strcmp(id(yr_sensor).state.c_str(), "snowy")  == 0) ? id(snowy)
  #         : (strcmp(id(yr_sensor).state.c_str(), "rainy")  == 0) ? id(rainy)
  #         : (strcmp(id(yr_sensor).state.c_str(), "fog")  == 0) ? id(fog)
  #         : id(sunny);
```

**Comment by clydebarrow** [comment]
An LVGL image object is not the same as an ESPHome image object, so you have to use a conversion function. As a tip, if you're going to write lambdas accessing widgets, it's useful to examine the generated main.cpp file to see how it's supposed to be done. For example, given this YAML:
```
            widgets:
              - image:
                  src: cat_img
                  bg_opa: TRANSP
                  align: bottom_right
```
When we look in the generated main.cpp file (under `.esphome/build/<device name>/src/`) and look for the corresponding code we find this:
```
      #line 568 "lvgl-package.yaml"
      lv_img_t_id = lv_img_create(lv_button);
      lv_obj_set_style_align(lv_img_t_id, LV_ALIGN_BOTTOM_RIGHT, LV_PART_MAIN);
      lv_obj_set_style_bg_opa(lv_img_t_id, LV_OPA_TRANSP, LV_PART_MAIN);
      lv_img_set_src(lv_img_t_id, lv_img_from(cat_img));
```
Notice that the `set_src` call uses the function `lv_img_from` to convert an ESPHome image to an LVGL image. So in your lambda you would need something like `lv_img_from(id(fog))` instead of just `id(fog)`.

Caveat - this is an implementation detail that can (and in fact definitely will) change in the future. For this reason I'd actually recommend not using a lambda to generate the image source, but use a conditional like this:
```
script:
  id: update_weather
  then:
    - if:
        condition:
          lambda: return id(condition).state == "sunny";
        then:
          lvgl.image.update:
            id: weather_image
            src: sunny_image
    - if:
        condition:
          lambda: return id(condition).state == "cloudy";
        then:
          lvgl.image.update:
            id: weather_image
            src: cloudy_image
```

There might be a better way to do it in the future, but this way should at least not break any time soon.
